version: 2.0
jobs:
  one:
    docker:
      - image: santosh9988/nginx
        auth:
          username: $dockerhub_username
          password: $dockerhub_password
      steps:
        - checkout
        - run: uname  -a
        - run: apt-get update -y
        - run: apt-get install git -y
        - run: git --version
jobs:
   two:
     build:
      docker:
        - image: santosh9988/nginx
      steps:
        - checkout
        - run: apt-get install openssh-server
        - run: systemctl enable ssh
 workflows:
   version: 2.0
   one_and two:
    jobs:
     - one
     - two
