version: 2.0
jobs:
  build:
    docker:
      - image: santosh9988/nginx
    steps:
      - checkout
      - run: uname  -a
      - run: apt-get update -y
      - run: apt-get install git -y
      - run: git --version
