version: 2
jobs:
 one:
   docker:
     - image: circleci/node:4.8.2
   steps:
        - checkout
        - run: uname  -a
        - run: sudo apt-get update -y
        - run: sudo apt-get install git -y
        - run: sudo git --version

 two:
  docker:
    - image: circleci/node:4.8.2
  steps:
    - checkout
    - run: which git


workflows:
  version: 2
  one_and_two:
    jobs:
     - one
     - two:
        requires:
         - one
